### ISSUE TITLE
Code release

### ISSUE THREAD

**Issue by natureyoo** [MKashifAli/MetaVideoStab#1]
Hi, thank you for your amazing work! When will you release the code?

**Comment by MKashifAli** [comment]
Hello, Thank you for the comment, I have been quite busy nowadays and haven't had the chance to clean the code but hopefully, I will do it over the coming weekend and will release it soon.

**Comment by MKashifAli** [comment]
Hello, Sorry for the delay in the code release, I have uploaded the cleaned (almost rewritten) code and will upload the checkpoints soon. Please help me test the code as I have not tested it yet but it should work, if there are any bugs, please let me know and I will get to them as soon as I get enough time. Thanks in advance 😃
