### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by 406809573** [MKashifAli/MetaVideoStab#3]
Hello, these modules (
channelnorm-cuda==0.0.0
correlation-cuda==0.0.0
resample2d-cuda==0.0.0)
 listed in the "environment.yml" could not be install by Pip directly:

(mvs) kk@kk-C321-XS4:~$ pip install channelnorm-cuda
ERROR: Could not find a version that satisfies the requirement channelnorm-cuda (from versions: none)
ERROR: No matching distribution found for channelnorm-cuda

**Comment by wangli07115** [comment]
os.environ['CUDA_VISIBLE_DEVICES'] = '4' 改为0

**Comment by wangli07115** [comment]
> Hello, these modules ( channelnorm-cuda==0.0.0 correlation-cuda==0.0.0 resample2d-cuda==0.0.0) listed in the "environment.yml" could not be install by Pip directly:
> 
> (mvs) kk@kk-C321-XS4:~$ pip install channelnorm-cuda ERROR: Could not find a version that satisfies the requirement channelnorm-cuda (from versions: none) ERROR: No matching distribution found for channelnorm-cuda

test_xxx.py
os.environ['CUDA_VISIBLE_DEVICES'] = '4'  改为
os.environ['CUDA_VISIBLE_DEVICES'] = '0'

**Comment by MKashifAli** [comment]
Please read the "README.md" carefully as in the first line of the "Installation" section it says "First, compile the dependencies for PWCNet from their official repository, as GlobalFlowNet uses a modified version of PWCNet.". Therefore, you can either go to the FlowNet2.0 repository or the PWCNet repository to compile these modules.
