### ISSUE TITLE
No module named 'contextual_loss'

### ISSUE THREAD

**Issue by wangli07115** [MKashifAli/MetaVideoStab#4]

**Comment by MKashifAli** [comment]
Please do not ignore the environmental inconsistencies. This error suggests that you had errors while creating the required environment but moved to testing despite those errors. Go over the instructions clearly and make sure you have the required modules for flow estimation and warping and make sure you have no issues with the environment and then you can start testing. Furthermore, you can install contextual_loss from this repository: https://github.com/S-aiueo32/contextual_loss_pytorch
